version: "3.4"

services:
  apiproject:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 8080:8080
    command: ["node", "--inspect=0.0.0.0:8080", "index.js"]
