version: "3.4"

services:
  mysqldb:
    container_name: database
    image: mysql:8
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 8080:8080
    expose:
      - 8080
    networks:
      - docker-nodesql

  apiproject:
    container_name: api-project
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    networks:
      - docker-nodesql

networks:
  docker-nodesql:
