version: "3.4"

services:
  mysqldb:
    container_name: database
    build:
      context: .
    environment:
      MYSQL_USER: "root"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 8080:8080
    expose:
      - 8080

  apiproject:
    container_name: api-project
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysqldb:
          - condition: service_healthy
